name: release-notes
on:
  push:
    tags: ['v*']
  workflow_dispatch:
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        id: vars        
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Run release.notes image
        uses: infobloxopen/github.release.notes@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.vars.outputs.tag }}
